---  
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-site
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: fornt-end
          image: hub.kce.ksyun.com/kbdp/nginx:1.0
          ports:
            - containerPort: 80
