apiVersion: v1
kind: Pod
metadata:
  name: pod-test
  labels:
    os: centos
spec:
  containers:
  - name: hello
    image: hub.kce.ksyun.com/kbdp/centos:latest
    imagePullPolicy: Never
    env: 
    - name: Test
      value: "123456"
    command: ["bash","-c","while 1;do date; sleep 1 ; done"]
  restartPolicy: Always
