apiVersion: v1
kind: Pod
metadata:
  name: pod-test
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: nginx:1.11.4-alpine
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
