apiVersion: v1
kind: Pod
metadata:
  name: test-pod-23
spec:
  containers:
  - name: test-service-pod-23
    image: hub.kce.ksyun.com/kbdp/nginx:1.0
    command: ["/bin/bash","-c","env"]
  imagePullSecrets:
  - name: myregistrykey
