apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-rolebinding
  namespace: kube-system
subjects:
- kind: User
  name: admin
  apiGroup: ""
roleRef:
  kind: Role
  name: admin-role
  apiGroup: ""
