apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: hub.kce.ksyun.com/kbdp/nginx:1.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
  restartPolicy: Always
