apiVersion: v1
kind: Pod
metadata:
  name: secret3-pod
spec:
  containers:
  - name: secret3pod
    image: hub.kce.ksyun.com/ksyun/busybox:mp
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret
      items:
      - key: username
        path: my-group/my-username
