apiVersion: v1
kind: Pod
metadata:  
  name: nginx-2 
  labels:    
    app: nginx-2
spec:  
  containers:  
  - name: nginx    
    image: hub.kce.ksyun.com/kbdp/nginx:1.0
    ports:    
    - containerPort: 80

